import { EvInfo, EvType } from "./types";
import { Utils } from "./utils/Utils";
import path from "path";

export const evInfo: EvInfo[] = [
  {
    id: "EV001",
    name: "EV001",
    totalDistanceTravelled: 0,
    hazard: "No",
    tirePressure: 0,
    costToKm: 6,
    features: "None",
    maintenanceNeeded: "No",
    chargingStatus: false,
    range: 25,
    typeOfVehicle: EvType.LOW,
    maxRange: 25,
    image: "veryLowEv.jpg",
    chargingPercentage: Math.floor(Math.random() * (100 - 50 + 1)) + 50,
  },
  {
    id: "EV002",
    name: "EV002",
    totalDistanceTravelled: 0,
    hazard: "No",
    tirePressure: 0,
    costToKm: 8,
    features: "None",
    maintenanceNeeded: "No",
    chargingStatus: false,
    range: 40,
    typeOfVehicle: EvType.LOW,
    maxRange: 40,
    image: "lowEv.jpg",
    chargingPercentage: Math.floor(Math.random() * (100 - 50 + 1)) + 50,
  },
  {
    id: "EV003",
    name: "EV003",
    totalDistanceTravelled: 0,
    hazard: "No",
    tirePressure: 0,
    costToKm: 8.2,
    features: "None",
    maintenanceNeeded: "No",
    chargingStatus: false,
    range: 75,
    typeOfVehicle: EvType.LOW,
    maxRange: 75,
    image: "mediumEv.jpg",
    chargingPercentage: Math.floor(Math.random() * (100 - 50 + 1)) + 50,
  },
  {
    id: "EV004",
    name: "EV004",
    totalDistanceTravelled: 0,
    hazard: "No",
    tirePressure: 0,
    costToKm: 8.5,
    features: "None",
    maintenanceNeeded: "No",
    chargingStatus: false,
    range: 100,
    typeOfVehicle: EvType.LOW,
    maxRange: 100,
    image: "highEv.jpg",
    chargingPercentage: Math.floor(Math.random() * (100 - 50 + 1)) + 50,
  },
  {
    id: "EV005",
    name: "EV005",
    totalDistanceTravelled: 0,
    hazard: "No",
    tirePressure: 0,
    costToKm: 8.8,
    features: "None",
    maintenanceNeeded: "No",
    chargingStatus: false,
    range: 120,
    typeOfVehicle: EvType.LOW,
    maxRange: 120,
    image: "veryHighEv.jpg",
    chargingPercentage: Math.floor(Math.random() * (100 - 50 + 1)) + 50,
  },
];

export const ROOT_DIR = path.resolve(__dirname, "..");
